export const ROUTE_HOME = '/'
export const ROUTE_USER_PROFILE = '/profile/'
export const ROUTE_DASHBOARD = '/dashboard'
export const ROUTE_MY_PROFILE = '/my-profile'
export const ROUTE_SIGN_IN = '/sign-in'
export const ROUTE_NOT_FOUND = '/404'
